### ISSUE TITLE
[Bug] strange bug when folded

### ISSUE THREAD

**Issue by mr-d-r** [Superschnizel/obisdian-fast-text-color#37]
**Version**
1.1.2

**Describe the bug**
error occures when the section is folded 
no error when the section is unfolded

i mean error when all colorization disappears:
app.js:1 Error: Ranges must be added sorted by `from` position and `startSide`
    at e.addInner (app.js:1:297087)
    at e.add (app.js:1:296861)
    at enter (plugin:fast-text-color:817:19)
    at e.iterate (app.js:1:551900)
    at su.iterate (app.js:1:2372520)
    at handleExpression (plugin:fast-text-color:797:32)
    at enter (plugin:fast-text-color:778:11)
    at e.iterate (app.js:1:551900)
    at su.iterate (app.js:1:2372520)
    at TextColorViewPlugin.buildDecorations (plugin:fast-text-color:768:51)
Hi @ app.js:1
e.update @ app.js:1
e.updatePlugins @ app.js:1
e.update @ app.js:1
dispatchTransactions @ app.js:1
e.dispatch @ app.js:1
vg @ app.js:1
bg @ app.js:1
p @ app.js:1
Jo @ app.js:1
keydown @ app.js:1
(anonymous) @ app.js:1
e.runHandlers @ app.js:1
e.handleEvent @ app.js:1

**To Reproduce**
scenario 1:
1. load attached fast.text.color.bug.movies.md
2. open it
3. go to "fast text color bug1" and fold it  ![1 before fold 2024-10-26_230021](https://github.com/user-attachments/assets/8febb768-2848-40b3-af1c-b1bd2e3e030f)

4. scroll down with arrow keys  ![2 after fold and scroll down 2024-10-26_230107](https://github.com/user-attachments/assets/098bc681-ba55-449d-8742-401593c4df9b)
5. colors are gone and error "app.js:1 Error: Ranges must be added sorted by `from` position and `startSide`" appears

scenario 2:
1. reopen fast.text.color.bug.movies.md after "fast text color bug1" was previously folded
2. colors are fine
3. scroll down with arrow keys
4. as soon cursor passes folded "fast text color bug1" colors disappeared & error occures

scenario 3:
1. reopen fast.text.color.bug.movies.md after "fast text color bug1" was previously UNfolded
2. scroll down with arrow keys
3. colors are OK & no error

**Expected behavior**
Please fix this bug

[▪︎ fast text color bug movies.md](https://github.com/user-attachments/files/17531965/fast.text.color.bug.movies.md)
![image](https://github.com/user-attachments/assets/0bbe8c61-19f7-4f78-a959-e869a28db374)

**Comment by Superschnizel** [comment]
In 1.1.3 this is now fixed in live preview mode. there are still some issues with reading mode.

**Comment by mr-d-r** [comment]
thank you for the update.
but unfortunately the problem still persists
![image](https://github.com/user-attachments/assets/0b032b43-9b67-4969-a234-caf65c5ebf24)
![image](https://github.com/user-attachments/assets/9470646c-f5cc-481a-ace6-ee07601bdd7c)

**Comment by mr-d-r** [comment]
is it possible to make a configuration flag to change this behaviour?

**Comment by mr-d-r** [comment]
is it possible to colorize until "=~" ignoring empty lines?
and add a configuration flag to customize this behaviour?
